server:
  port: 8000

spring:
  profiles:
    active: local

  cloud:
    gateway:
      routes:
        - id: web
          uri: http://localhost:8002
          predicates:
            - Path=/web/**
          filters:
            - RewritePath=/web/?(?<segment>.*), /$\{segment}
        - id: backend
          uri: http://localhost:8003
          predicates:
            - Path=/backend/**
          filters:
            - RewritePath=/backend/?(?<segment>.*), /$\{segment}

knife4j:
  gateway:
    enabled: true
    strategy: manual
    routes:
      - name: web
        url: /web/v3/api-docs/user-api
        service-name: web
        context-path: /web
        order: 1
      - name: backend-sapi
        url: /backend/v3/api-docs/server-api
        service-name: backend
        context-path: /backend
        order: 2