server:
  port: 8000

spring:
  profiles:
    active: local

  cloud:
    gateway:
      routes:
        - id: web
          uri: http://localhost:8002
          predicates:
            - Path=/**

knife4j:
  gateway:
    enabled: true
    strategy: manual
    routes:
      - name: web
        url: /v3/api-docs/user-api
        service-name: web
        order: 1