server:
  port: 8003

spring:
  profiles:
    active: local

  webflux:
    base-path: /backend

  application:
    name: web
  main:
    web-application-type: reactive

  r2dbc:
    url: r2dbc:mysql://localhost:3306/mytest
    username: root
    password: -----


logging:
  level:
    org.springframework.r2dbc: debug


springdoc:
  group-configs:
    - group: 'server-api'
      paths-to-match:
        - /**